name: Release Process

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.7

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate version
        run: |
          # Extract version from composer.json
          COMPOSER_VERSION=$(grep '"version"' composer.json | cut -d'"' -f4)
          # Extract version from tag (remove 'v' prefix)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          # Compare versions
          if [ "$COMPOSER_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: composer.json ($COMPOSER_VERSION) doesn't match tag ($TAG_VERSION)"
            exit 1
          fi

      # This job depends on the test workflow passing
      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'test' # This is the job name from theme-test.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          generate_release_notes: true
