name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4
        with:
          path: theme

      - name: Create test directory
        run: |
          mkdir drupal-test
          cd drupal-test

      - name: Install DDEV
        working-directory: drupal-test
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Setup Docker
        working-directory: drupal-test
        run: |
          docker --version
          docker compose version

      - name: Configure and start DDEV
        working-directory: drupal-test
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Install Drupal
        working-directory: drupal-test
        run: |
          # Create fresh Drupal project
          ddev composer create --no-install "drupal/recommended-project:^10"

          # Configure Composer
          ddev composer config minimum-stability dev
          ddev composer config prefer-stable true

          # Allow plugins
          ddev composer config allow-plugins true --no-plugins

          # Install dependencies
          ddev composer require drush/drush
          ddev composer require drupal/bootstrap:^5.0
          ddev composer require drupal/admin_toolbar
          ddev composer require drupal/paragraphs

          # Create settings file
          ddev exec mkdir -p web/sites/default/files
          ddev exec chmod 777 web/sites/default/files
          ddev exec cp web/sites/default/default.settings.php web/sites/default/settings.php
          ddev exec chmod 777 web/sites/default/settings.php

      - name: Copy theme
        working-directory: drupal-test
        run: |
          mkdir -p web/themes/custom
          cp -r ../theme web/themes/custom/du_bootstrap

      - name: Setup Database and Settings
        working-directory: drupal-test
        run: |
          # Create settings file
          ddev exec mkdir -p web/sites/default/files
          ddev exec chmod 777 web/sites/default/files
          ddev exec cp web/sites/default/default.settings.php web/sites/default/settings.php
          ddev exec chmod 777 web/sites/default/settings.php

          # Create settings.local.php with database configuration
          cat << 'EOSETTINGS' > settings.local.php
          <?php
          $databases['default']['default'] = [
            'database' => 'db',
            'username' => 'db',
            'password' => 'db',
            'host' => 'db',
            'port' => '3306',
            'driver' => 'mysql',
            'prefix' => '',
          ];
          EOSETTINGS

          # Copy settings file into container
          ddev exec cp settings.local.php web/sites/default/settings.local.php
          ddev exec "echo 'include \$app_root . \"/\" . \$site_path . \"/settings.local.php\";' >> web/sites/default/settings.php"

          # Verify database connection
          ddev mysql -e "SHOW DATABASES;"

      - name: Install site
        working-directory: drupal-test
        run: |
          # Install Drupal using standard profile
          ddev exec drush site:install standard \
            --account-name=admin \
            --account-pass=admin \
            --site-name="Test Site" \
            --yes

          # Verify installation
          ddev exec drush status

          # Enable theme
          ddev exec drush theme:enable du_bootstrap
          ddev exec drush config-set system.theme default du_bootstrap -y
          ddev exec drush cr
