name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4
        with:
          path: theme

      - name: Create test directory
        run: mkdir drupal-test

      - name: Install DDEV
        working-directory: drupal-test
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Configure and start DDEV
        working-directory: drupal-test
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Install Drupal with Profile
        working-directory: drupal-test
        run: |
          # Backup and clear directory
          mv .ddev ../ddev-backup
          rm -rf *

          # Clone and setup repository
          git clone https://github.com/University-of-Denver/drupal-composer-managed.git .
          rm -rf .ddev
          mv ../ddev-backup .ddev

          # Install dependencies and copy theme
          ddev composer install
          mkdir -p web/themes/custom
          cp -r ../theme web/themes/custom/du_bootstrap

      - name: Setup Database
        working-directory: drupal-test
        run: |
          mkdir -p web/sites/default/files
          chmod 777 web/sites/default/files

          cat << 'EOSETTINGS' > web/sites/default/settings.local.php
          <?php
          $databases['default']['default'] = [
            'database' => 'db',
            'username' => 'db',
            'password' => 'db',
            'host' => 'db',
            'port' => '3306',
            'driver' => 'mysql',
            'prefix' => '',
          ];
          $settings['hash_salt'] = 'test';
          EOSETTINGS

          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "include \$app_root . '/' . \$site_path . '/settings.local.php';" >> web/sites/default/settings.php

      - name: Install site
        working-directory: drupal-test
        run: |
          ddev exec drush site:install ducore \
            --account-name=admin \
            --account-pass=admin \
            --site-name="Test Site" \
            --yes

          ddev exec drush theme:enable du_bootstrap
          ddev exec drush config-set system.theme default du_bootstrap -y
          ddev exec drush cr