name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Install DDEV
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Setup Docker
        run: |
          docker --version
          docker compose version

      - name: Configure and start DDEV
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Install Composer Dependencies
        run: |
          ddev composer require drush/drush
          ddev composer require drupal/core-recommended:^10
          ddev composer require drupal/core-composer-scaffold:^10

      - name: Install site
        run: |
          ddev drush si ducore -y
          ddev drush status
          # Capture any errors in the watchdog
          ddev drush wd-show

      - name: Check theme
        run: |
          ddev drush theme:enable du_bootstrap
          ddev drush config-get system.theme default
