name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Setup DDEV Drupal Contrib
        run: |
          curl -LO https://raw.githubusercontent.com/ddev/ddev-drupal-contrib/main/install.sh
          bash install.sh

      - name: Configure project
        run: |
          # We might need to adjust composer config here
          # but let's first verify what's actually needed
          ddev composer config --list

      - name: Start DDEV
        run: |
          ddev start
          ddev auth ssh

      - name: Install site
        run: |
          ddev drush si ducore -y
          ddev drush status
          # Capture any errors in the watchdog
          ddev drush wd-show

      - name: Check theme
        run: |
          ddev drush theme:enable du_bootstrap
          ddev drush config-get system.theme default

name: Release Process

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.7

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate version
        run: |
          # Extract version from composer.json
          COMPOSER_VERSION=$(grep '"version"' composer.json | cut -d'"' -f4)
          # Extract version from tag (remove 'v' prefix)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          # Compare versions
          if [ "$COMPOSER_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: composer.json ($COMPOSER_VERSION) doesn't match tag ($TAG_VERSION)"
            exit 1
          fi

      # This job depends on the test workflow passing
      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'test' # This is the job name from theme-test.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          generate_release_notes: true