name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4
        with:
          path: theme

      - name: Create test directory
        run: |
          mkdir drupal-test
          cd drupal-test

      - name: Install DDEV
        working-directory: drupal-test
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Setup Docker
        working-directory: drupal-test
        run: |
          docker --version
          docker compose version

      - name: Configure and start DDEV
        working-directory: drupal-test
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Install Drupal
        working-directory: drupal-test
        run: |
          # Create fresh Drupal project
          ddev composer create --no-install "drupal/recommended-project:^10"

          # Configure Composer
          ddev composer config minimum-stability dev
          ddev composer config prefer-stable true

          # Allow plugins
          ddev composer config allow-plugins true --no-plugins

          # Install core and required modules
          ddev composer require --no-update "drupal/core:^10"
          ddev composer require --no-update "drupal/core-recommended:^10"
          ddev composer require --no-update "drupal/core-composer-scaffold:^10"
          ddev composer require --no-update "drupal/core-project-message:~10.3.2"
          ddev composer require --no-update "drush/drush:^12"

          # Parse ducore.info.yml and install required modules
          CORE_MODULES=$(grep -E '^  - ' ../theme/web/profiles/custom/ducore/ducore.info.yml | grep -v '^  - system\|^  - user\|^  - node\|^  - block\|^  - field\|^  - file\|^  - filter\|^  - image\|^  - text\|^  - views\|^  - taxonomy\|^  - path\|^  - datetime\|^  - options\|^  - menu_link_content\|^  - dblog\|^  - block_content\|^  - media' | sed 's/^  - /drupal\//' | tr '\n' ' ')

          for MODULE in $CORE_MODULES
          do
            ddev composer require --no-update $MODULE
          done

          # Update everything
          ddev composer update --with-all-dependencies

      - name: Copy DU Core profile
        working-directory: drupal-test
        run: |
          # Create profiles directory if it doesn't exist
          mkdir -p web/profiles/custom

          # Clone the ducore profile
          git clone https://github.com/University-of-Denver/drupal-composer-managed.git temp
          cp -r temp/web/profiles/custom/ducore web/profiles/custom/
          rm -rf temp

      - name: Install site
        working-directory: drupal-test
        run: |
          # Install Drupal using ducore profile
          ddev exec drush site:install ducore \
            --account-name=admin \
            --account-pass=admin \
            --site-name="Test Site" \
            --yes

          # Enable theme
          ddev exec drush theme:enable du_bootstrap
          ddev exec drush config-set system.theme default du_bootstrap -y
          ddev exec drush cr
