name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4

      - name: Install DDEV
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Setup Docker
        run: |
          docker --version
          docker compose version

      - name: Configure and start DDEV
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Configure Composer
        run: |
          ddev composer config repositories.drupal composer https://packages.drupal.org/8
          ddev composer config minimum-stability dev
          ddev composer config prefer-stable true
          # Allow required plugins
          ddev composer config allow-plugins.drupal/core-composer-scaffold true
          ddev composer config allow-plugins.composer/installers true
          ddev composer config allow-plugins.drupal/core-project-message true

      - name: Install Composer Dependencies
        run: |
          ddev composer require --no-update drupal/core-recommended:^10
          ddev composer require --no-update drupal/core-composer-scaffold:^10
          ddev composer require --no-update drush/drush
          ddev composer require --no-update drupal/bootstrap:^5.0
          ddev composer update

      - name: Setup DU Core Profile
        run: |
          # Create profiles directory if it doesn't exist
          ddev exec mkdir -p web/profiles/custom
          # Clone DU Core profile
          ddev exec git clone https://github.com/University-of-Denver/drupal-composer-managed.git /tmp/drupal-composer-managed
          ddev exec cp -r /tmp/drupal-composer-managed/web/profiles/custom/ducore web/profiles/custom/
          # Clean up
          ddev exec rm -rf /tmp/drupal-composer-managed

      - name: Install site
        run: |
          ddev drush si ducore -y
          ddev drush status
          # Capture any errors in the watchdog
          ddev drush wd-show

      - name: Check theme
        run: |
          ddev drush theme:enable du_bootstrap
          ddev drush config-get system.theme default
