name: DU Bootstrap Theme Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theme
        uses: actions/checkout@v4
        with:
          path: theme

      - name: Create test directory
        run: |
          mkdir drupal-test
          cd drupal-test

      - name: Install DDEV
        working-directory: drupal-test
        run: |
          curl -fsSL https://ddev.com/install.sh | bash
          ddev --version

      - name: Setup Docker
        working-directory: drupal-test
        run: |
          docker --version
          docker compose version

      - name: Configure and start DDEV
        working-directory: drupal-test
        run: |
          ddev config --project-type=drupal10 --docroot=web --create-docroot
          ddev start

      - name: Install Drupal
        working-directory: drupal-test
        run: |
          # Create fresh Drupal project
          ddev composer create --no-install "drupal/recommended-project:^10"

          # Configure Composer
          ddev composer config minimum-stability dev
          ddev composer config prefer-stable true

          # Allow plugins
          ddev composer config allow-plugins true --no-plugins

          # Install dependencies
          ddev composer require drush/drush
          ddev composer require drupal/bootstrap:^5.0
          ddev composer require drupal/admin_toolbar
          ddev composer require drupal/paragraphs

          # Create settings file
          ddev exec mkdir -p web/sites/default/files
          ddev exec chmod 777 web/sites/default/files
          ddev exec cp web/sites/default/default.settings.php web/sites/default/settings.php
          ddev exec chmod 777 web/sites/default/settings.php

      - name: Copy theme
        working-directory: drupal-test
        run: |
          mkdir -p web/themes/custom
          cp -r ../theme web/themes/custom/du_bootstrap

      - name: Install site
        working-directory: drupal-test
        run: |
          # Debug: List available installation profiles
          ddev drush pm:list --type=profile

          # Debug: Check Drupal status
          ddev drush status

          # Debug: List directory contents
          ddev exec ls -la web/core/profiles
          ddev exec ls -la web/profiles || true

          # Try installation with explicit DB URL and profile path
          ddev drush si standard \
            --db-url=mysql://db:db@db:3306/db \
            --site-name="Test Site" \
            --account-name=admin \
            --account-pass=admin \
            --root=/var/www/html/web \
            -y

          # If successful, enable theme
          if [ $? -eq 0 ]; then
            ddev drush theme:enable du_bootstrap
            ddev drush config-set system.theme default du_bootstrap -y
            ddev drush cr
            ddev drush status
            ddev drush wd-show
          fi
